import { router, useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { ActionButton } from '@/components/action-button';
import { FormField } from '@/components/form-field';
import { getLocalBusinessDate } from '@/domain/business-date';
import { formatCentavos, parseCurrencyToCentavos } from '@/domain/money';
import { finalizeAndRenderBillingStatement } from '@/features/billing-statements/billing-statement-pdf';
import { BillingDraftPriceChangedError, getBillingStatement } from '@/features/billing-statements/billing-statement-repository';
import type { BillingStatementDetail } from '@/features/billing-statements/billing-statement-types';
import type { InitialPaymentSelection, PaymentMethod } from '@/features/payments/payment-types';
import { colors } from '@/theme/colors';

type Choice=InitialPaymentSelection['choice'];
const METHODS: Array<{value:PaymentMethod;label:string}>=[{value:'cash',label:'Cash'},{value:'bank_transfer',label:'Bank transfer'},{value:'e_wallet',label:'GCash / E-wallet'},{value:'check',label:'Check'},{value:'other',label:'Other'}];

export default function FinalizeBillingStatementScreen(){
  const{statementId}=useLocalSearchParams<{statementId:string}>();const db=useSQLiteContext();
  const[statement,setStatement]=useState<BillingStatementDetail|null>(null);const[choice,setChoice]=useState<Choice>('pay_later');const[amount,setAmount]=useState('');const[businessDate,setBusinessDate]=useState(getLocalBusinessDate());const[backdateReason,setBackdateReason]=useState('');const[method,setMethod]=useState<PaymentMethod>('cash');const[reference,setReference]=useState('');const[note,setNote]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
  useEffect(()=>{if(statementId)void getBillingStatement(db,statementId).then(setStatement).catch((e:unknown)=>setError(e instanceof Error?e.message:'Could not load statement.'));},[db,statementId]);
  const finalize=useCallback(async(policy:'reject'|'keep-draft'|'use-current'='reject')=>{if(!statement)return;setBusy(true);setError(null);try{const selection:InitialPaymentSelection=choice==='pay_later'?{choice}:{choice,payment:{amountCentavos:choice==='paid_in_full'?statement.discountedTotalCentavos:parseCurrencyToCentavos(amount),businessDate,backdateReason,method,referenceNumber:reference,note}};const result=await finalizeAndRenderBillingStatement(db,statementId,policy,selection);Alert.alert('Statement finalized',`${result.bsNumber} and ${result.paymentId?'its Payment Acknowledgment':'the Billing Statement PDF'} are ready.`);router.replace({pathname:'/billing-statements/[statement-id]',params:{'statement-id':statementId}});}catch(e){if(e instanceof BillingDraftPriceChangedError)Alert.alert('Prices changed',e.message,[{text:'Cancel',style:'cancel'},{text:'Keep draft prices',onPress:()=>void finalize('keep-draft')},{text:'Use current prices',onPress:()=>void finalize('use-current')}]);else{const latest=await getBillingStatement(db,statementId);if(latest?.documentState==='finalized'){Alert.alert('Finalized with a PDF issue','The business records are safe. Open the statement or payment to retry its PDF.');router.replace({pathname:'/billing-statements/[statement-id]',params:{'statement-id':statementId}});}else setError(e instanceof Error?e.message:'Could not finalize statement.');}}finally{setBusy(false);}},[amount,backdateReason,businessDate,choice,db,method,note,reference,statement,statementId]);
  if(!statement)return <View style={styles.center}><Text selectable style={styles.help}>{error??'Loading…'}</Text></View>;
  const needsPayment=choice!=='pay_later';return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content}><View style={styles.summary}><Text selectable style={styles.eyebrow}>FINALIZATION</Text><Text selectable style={styles.total}>{formatCentavos(statement.discountedTotalCentavos)}</Text><Text selectable style={styles.help}>Finalization freezes the statement, allocates its number, and posts direct inventory sales.</Text></View><Text selectable style={styles.title}>Payment choice</Text><View style={styles.choices}><ChoiceButton label="Pay Later" detail="No initial payment" selected={choice==='pay_later'} onPress={()=>setChoice('pay_later')}/><ChoiceButton label="Paid in Full" detail={formatCentavos(statement.discountedTotalCentavos)} selected={choice==='paid_in_full'} onPress={()=>setChoice('paid_in_full')}/><ChoiceButton label="Down Payment" detail="One deposit, then the full balance" selected={choice==='down_payment'} onPress={()=>setChoice('down_payment')}/></View>{needsPayment?<View style={styles.form}>{choice==='down_payment'?<FormField label="Down payment amount" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="0.00"/>:<View style={styles.locked}><Text selectable style={styles.lockedLabel}>Payment amount</Text><Text selectable style={styles.lockedValue}>{formatCentavos(statement.discountedTotalCentavos)}</Text></View>}<FormField label="Payment business date" value={businessDate} onChangeText={setBusinessDate} placeholder="YYYY-MM-DD"/>{businessDate<getLocalBusinessDate()?<FormField label="Backdate reason" value={backdateReason} onChangeText={setBackdateReason}/>:null}<Text selectable style={styles.fieldLabel}>Method</Text><View style={styles.pills}>{METHODS.map((entry)=><Pressable key={entry.value} accessibilityRole="button" onPress={()=>setMethod(entry.value)} style={[styles.pill,method===entry.value&&styles.activePill]}><Text selectable style={[styles.pillText,method===entry.value&&styles.activePillText]}>{entry.label}</Text></Pressable>)}</View>{method!=='cash'?<FormField label="Required reference" value={reference} onChangeText={setReference} placeholder="Transaction or check reference"/>:null}<FormField label="Note (optional)" value={note} onChangeText={setNote}/></View>:null}{error?<Text selectable style={styles.error}>{error}</Text>:null}<ActionButton disabled={busy} onPress={()=>void finalize()}>{busy?'Finalizing…':'Finalize and generate documents'}</ActionButton></ScrollView>;
}
function ChoiceButton({label,detail,selected,onPress}:{label:string;detail:string;selected:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.choice,selected&&styles.choiceSelected]}><View><Text selectable style={[styles.choiceTitle,selected&&styles.choiceTitleSelected]}>{label}</Text><Text selectable style={styles.help}>{detail}</Text></View><Text selectable style={styles.check}>{selected?'●':'○'}</Text></Pressable>}
const styles=StyleSheet.create({content:{gap:16,padding:18,paddingBottom:44},center:{flex:1,alignItems:'center',justifyContent:'center'},summary:{gap:5,padding:17,backgroundColor:'#eaf2ff',borderRadius:16,borderCurve:'continuous'},eyebrow:{color:colors.brandBlue,fontSize:10,fontWeight:'900',letterSpacing:1},total:{color:colors.brandNavy,fontSize:24,fontWeight:'900'},help:{color:colors.secondaryLabel,fontSize:12,lineHeight:18},title:{color:colors.label,fontSize:17,fontWeight:'900'},choices:{gap:8},choice:{minHeight:66,flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:14,borderWidth:1,borderColor:colors.separator,borderRadius:15,borderCurve:'continuous',backgroundColor:colors.surface},choiceSelected:{borderColor:colors.brandBlue,backgroundColor:'#eaf2ff'},choiceTitle:{color:colors.label,fontSize:15,fontWeight:'800'},choiceTitleSelected:{color:colors.brandNavy},check:{color:colors.brandBlue,fontSize:21},form:{gap:13,paddingTop:4},locked:{gap:4,padding:14,borderWidth:1,borderColor:colors.separator,borderRadius:12,backgroundColor:colors.surface},lockedLabel:{color:colors.secondaryLabel,fontSize:12,fontWeight:'700'},lockedValue:{color:colors.label,fontSize:18,fontWeight:'900'},fieldLabel:{color:colors.label,fontSize:14,fontWeight:'700'},pills:{flexDirection:'row',flexWrap:'wrap',gap:7},pill:{minHeight:40,justifyContent:'center',paddingHorizontal:12,borderWidth:1,borderColor:colors.separator,borderRadius:20,backgroundColor:colors.surface},activePill:{borderColor:colors.brandBlue,backgroundColor:'#eaf2ff'},pillText:{color:colors.secondaryLabel,fontSize:12,fontWeight:'800'},activePillText:{color:colors.brandNavy},error:{color:colors.error,fontSize:13,fontWeight:'600'}});
