import { Link, router, useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { memo, useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';

import { formatCentavos } from '@/domain/money';
import { listBillingStatements } from '@/features/billing-statements/billing-statement-repository';
import type { BillingStatementSummary } from '@/features/billing-statements/billing-statement-types';
import { colors } from '@/theme/colors';

const StatementRow=memo(function StatementRow({statement}:{statement:BillingStatementSummary}){const open=useCallback(()=>router.push({pathname:'/billing-statements/[statement-id]',params:{'statement-id':statement.id}}),[statement.id]);return <Pressable accessibilityRole="button" onPress={open} style={({pressed})=>[styles.row,pressed&&styles.pressed]}><View style={styles.rowCopy}><View style={styles.titleLine}><Text selectable style={styles.number}>{statement.bsNumber??'DRAFT'}</Text><Text selectable style={statement.documentState==='draft'?styles.draftBadge:statement.documentState==='voided'?styles.voidBadge:styles.finalBadge}>{statement.documentState.toUpperCase()}</Text></View><Text selectable style={styles.customer}>{statement.customerName}</Text><Text selectable style={styles.meta}>{statement.businessDate}</Text></View><View style={styles.amountCopy}><Text selectable style={styles.amount}>{formatCentavos(statement.discountedTotalCentavos)}</Text>{statement.documentState==='finalized'?<Text selectable style={styles.pdf}>PDF {statement.pdfState}</Text>:null}</View></Pressable>});

export default function BillingStatementsScreen(){const db=useSQLiteContext();const[rows,setRows]=useState<BillingStatementSummary[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{setRows(await listBillingStatements(db));}catch(e){setError(e instanceof Error?e.message:'Could not load billing statements.');}finally{setLoading(false);}},[db]);useFocusEffect(useCallback(()=>{void load();},[load]));return <FlatList contentInsetAdjustmentBehavior="automatic" contentContainerStyle={rows.length?styles.content:styles.emptyContent} data={rows} keyExtractor={(item)=>item.id} renderItem={({item})=><StatementRow statement={item}/>} ItemSeparatorComponent={()=><View style={styles.separator}/>} refreshing={loading&&rows.length>0} onRefresh={load} ListHeaderComponent={<View style={styles.header}><Text selectable style={styles.eyebrow}>BILLING STATEMENTS</Text><Text selectable style={styles.help}>Drafts are unnumbered. Finalization freezes charges and deducts stock for direct item sales.</Text><Link href="/billing-statements/new" asChild><Pressable accessibilityRole="button" style={styles.newButton}><Text selectable style={styles.newText}>New statement draft</Text></Pressable></Link>{error?<Text selectable style={styles.error}>{error}</Text>:null}</View>} ListEmptyComponent={loading?<ActivityIndicator color={colors.brandBlue} size="large"/>:<View style={styles.empty}><Text selectable style={styles.emptyTitle}>No billing statements yet</Text><Text selectable style={styles.help}>Create a draft for a registered customer.</Text></View>}/>;}

const styles=StyleSheet.create({content:{paddingHorizontal:18,paddingBottom:44},emptyContent:{flexGrow:1,paddingHorizontal:18,paddingBottom:44},header:{gap:10,paddingVertical:18},eyebrow:{color:colors.brandBlue,fontSize:11,fontWeight:'900',letterSpacing:1.2},help:{color:colors.secondaryLabel,fontSize:13,lineHeight:19},newButton:{minHeight:48,alignItems:'center',justifyContent:'center',backgroundColor:colors.brandBlue,borderRadius:14,borderCurve:'continuous'},newText:{color:'#fff',fontSize:15,fontWeight:'800'},row:{minHeight:88,flexDirection:'row',alignItems:'center',gap:12,paddingVertical:14},rowCopy:{flex:1,gap:4},titleLine:{flexDirection:'row',alignItems:'center',gap:8},number:{color:colors.label,fontSize:15,fontWeight:'900',fontVariant:['tabular-nums']},customer:{color:colors.label,fontSize:15,fontWeight:'700'},meta:{color:colors.secondaryLabel,fontSize:12},draftBadge:{color:colors.warning,fontSize:8,fontWeight:'900'},finalBadge:{color:colors.success,fontSize:8,fontWeight:'900'},voidBadge:{color:colors.error,fontSize:8,fontWeight:'900'},amountCopy:{alignItems:'flex-end',gap:4},amount:{color:colors.brandNavy,fontSize:14,fontWeight:'900'},pdf:{color:colors.secondaryLabel,fontSize:9,fontWeight:'800',textTransform:'uppercase'},separator:{height:StyleSheet.hairlineWidth,backgroundColor:colors.separator},empty:{flex:1,alignItems:'center',justifyContent:'center',gap:8,padding:28},emptyTitle:{color:colors.label,fontSize:20,fontWeight:'900'},error:{color:colors.error,fontSize:13},pressed:{opacity:.72}});
