import { router } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useCallback, useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { ActionButton } from '@/components/action-button';
import { FormField } from '@/components/form-field';
import { getLocalBusinessDate } from '@/domain/business-date';
import { createBillingStatementDraft, listFinalizedCsrsForCustomer } from '@/features/billing-statements/billing-statement-repository';
import { listCustomers } from '@/features/customers/customer-repository';
import type { CustomerSummary } from '@/features/customers/customer-types';
import { colors } from '@/theme/colors';

type CsrChoice={id:string;csrNumber:string;businessDate:string;availableLineCount:number};
export default function NewBillingStatementScreen(){const db=useSQLiteContext();const[customers,setCustomers]=useState<CustomerSummary[]>([]);const[customerId,setCustomerId]=useState('');const[csrs,setCsrs]=useState<CsrChoice[]>([]);const[csrId,setCsrId]=useState('');const[businessDate,setBusinessDate]=useState(getLocalBusinessDate());const[backdateReason,setBackdateReason]=useState('');const[error,setError]=useState<string|null>(null);const[saving,setSaving]=useState(false);useEffect(()=>{void listCustomers(db).then((r)=>setCustomers(r.filter((c)=>c.active))).catch((e:unknown)=>setError(e instanceof Error?e.message:'Could not load customers.'));},[db]);useEffect(()=>{setCsrId('');if(!customerId){setCsrs([]);return;}void listFinalizedCsrsForCustomer(db,customerId).then(setCsrs).catch((e:unknown)=>setError(e instanceof Error?e.message:'Could not load CSRs.'));},[customerId,db]);const create=useCallback(async()=>{setSaving(true);setError(null);try{const id=await createBillingStatementDraft(db,{customerId,serviceReportId:csrId||undefined,businessDate,backdateReason});router.replace({pathname:'/billing-statements/[statement-id]',params:{'statement-id':id}});}catch(e){setError(e instanceof Error?e.message:'Could not create draft.');}finally{setSaving(false);}},[backdateReason,businessDate,csrId,customerId,db]);return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content}><View style={styles.intro}><Text selectable style={styles.eyebrow}>UNNUMBERED DRAFT</Text><Text selectable style={styles.introText}>Choose a customer. Linking one finalized CSR is optional and makes its unbilled item usages available.</Text></View><Text selectable style={styles.title}>Customer</Text><View style={styles.choices}>{customers.map((customer)=><Choice key={customer.id} label={customer.name} selected={customer.id===customerId} onPress={()=>setCustomerId(customer.id)}/>)}</View>{customerId?<><Text selectable style={styles.title}>Optional CSR</Text><View style={styles.choices}><Choice label="No linked CSR" selected={!csrId} onPress={()=>setCsrId('')}/>{csrs.map((csr)=><Choice key={csr.id} label={`${csr.csrNumber} · ${csr.businessDate} · ${csr.availableLineCount} unbilled item(s)`} selected={csr.id===csrId} onPress={()=>setCsrId(csr.id)}/>)}</View></>:null}<FormField label="Business date" value={businessDate} onChangeText={setBusinessDate} placeholder="YYYY-MM-DD"/>{businessDate<getLocalBusinessDate()?<FormField label="Backdate reason" value={backdateReason} onChangeText={setBackdateReason} placeholder="Why this statement uses an earlier date"/>:null}{error?<Text selectable style={styles.error}>{error}</Text>:null}<ActionButton disabled={saving||!customerId} onPress={()=>void create()}>{saving?'Creating…':'Create draft'}</ActionButton></ScrollView>}
function Choice({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.choice,selected&&styles.selected]}><Text selectable style={[styles.choiceText,selected&&styles.selectedText]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({content:{gap:16,padding:18,paddingBottom:44},intro:{gap:6,padding:16,backgroundColor:'#eaf2ff',borderRadius:16,borderCurve:'continuous'},eyebrow:{color:colors.brandBlue,fontSize:10,fontWeight:'900',letterSpacing:1},introText:{color:colors.brandNavy,fontSize:14,lineHeight:20},title:{color:colors.label,fontSize:16,fontWeight:'900'},choices:{gap:8},choice:{minHeight:48,justifyContent:'center',paddingHorizontal:15,borderWidth:1,borderColor:colors.separator,borderRadius:14,borderCurve:'continuous',backgroundColor:colors.surface},selected:{borderColor:colors.brandBlue,backgroundColor:'#eaf2ff'},choiceText:{color:colors.label,fontSize:14,fontWeight:'700'},selectedText:{color:colors.brandNavy},error:{color:colors.error,fontSize:13,fontWeight:'600'}});
