import { router, useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { ActionButton } from '@/components/action-button';
import { FormField } from '@/components/form-field';
import { getBillingStatement, voidBillingStatement } from '@/features/billing-statements/billing-statement-repository';
import type { BillingStatementDetail } from '@/features/billing-statements/billing-statement-types';
import { colors } from '@/theme/colors';

export default function VoidBillingStatementScreen(){const{statementId}=useLocalSearchParams<{statementId:string}>();const db=useSQLiteContext();const[statement,setStatement]=useState<BillingStatementDetail|null>(null);const[reason,setReason]=useState('');const[choices,setChoices]=useState<Record<string,boolean>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);useEffect(()=>{if(statementId)void getBillingStatement(db,statementId).then(setStatement).catch((e:unknown)=>setError(e instanceof Error?e.message:'Could not load statement.'));},[db,statementId]);const items=useMemo(()=>{const result=new Map<string,string>();for(const line of statement?.lines??[])if(line.lineType==='item'&&!line.sourceCsrUsageId&&line.itemId)result.set(line.itemId,line.description);return [...result.entries()].map(([id,name])=>({id,name}));},[statement]);const submit=useCallback(async()=>{if(!statementId)return;setBusy(true);setError(null);try{await voidBillingStatement(db,statementId,reason,items.map((item)=>({itemId:item.id,returnedToStock:choices[item.id]??false})));router.back();}catch(e){setError(e instanceof Error?e.message:'Could not void statement.');}finally{setBusy(false);}},[choices,db,items,reason,statementId]);return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content}><View style={styles.warning}><Text selectable style={styles.warningTitle}>Void finalized statement</Text><Text selectable style={styles.warningText}>A paid statement cannot be voided. The number stays used and the frozen PDF remains in history.</Text></View><FormField label="Required reason" value={reason} onChangeText={setReason} multiline placeholder="Why is this statement being voided?"/>{items.length?<View style={styles.section}><Text selectable style={styles.title}>Direct item disposition</Text><Text selectable style={styles.help}>Choose whether each directly billed item physically returned to stock. CSR-linked items are excluded because their stock was deducted by the CSR.</Text>{items.map((item)=><View key={item.id} style={styles.item}><Text selectable style={styles.itemName}>{item.name}</Text><View style={styles.choices}>{[false,true].map((value)=><Pressable key={String(value)} accessibilityRole="button" onPress={()=>setChoices((current)=>({...current,[item.id]:value}))} style={[styles.choice,(choices[item.id]??false)===value&&styles.selected]}><Text selectable style={[styles.choiceText,(choices[item.id]??false)===value&&styles.selectedText]}>{value?'Returned':'Not returned'}</Text></Pressable>)}</View></View>)}</View>:<Text selectable style={styles.help}>This statement has no direct item sale, so no stock disposition is needed.</Text>}{error?<Text selectable style={styles.error}>{error}</Text>:null}<ActionButton disabled={busy||!reason.trim()} variant="danger" onPress={()=>void submit()}>{busy?'Voiding…':'Void statement'}</ActionButton></ScrollView>}
const styles=StyleSheet.create({content:{gap:16,padding:18,paddingBottom:44},warning:{gap:6,padding:16,backgroundColor:'#fee2e2',borderRadius:16,borderCurve:'continuous'},warningTitle:{color:colors.error,fontSize:17,fontWeight:'900'},warningText:{color:'#7f1d1d',fontSize:13,lineHeight:19},section:{gap:11},title:{color:colors.label,fontSize:16,fontWeight:'900'},help:{color:colors.secondaryLabel,fontSize:13,lineHeight:19},item:{gap:8,paddingVertical:8},itemName:{color:colors.label,fontSize:14,fontWeight:'800'},choices:{flexDirection:'row',gap:8},choice:{minHeight:40,justifyContent:'center',paddingHorizontal:13,borderWidth:1,borderColor:colors.separator,borderRadius:20,backgroundColor:colors.surface},selected:{borderColor:colors.brandBlue,backgroundColor:'#eaf2ff'},choiceText:{color:colors.secondaryLabel,fontSize:12,fontWeight:'800'},selectedText:{color:colors.brandNavy},error:{color:colors.error,fontSize:13,fontWeight:'600'}});
