import { router, useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { memo, useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';

import { formatCentavos } from '@/domain/money';import { listPayments } from '@/features/payments/payment-repository';import type { PaymentSummary } from '@/features/payments/payment-types';import { colors } from '@/theme/colors';
const PaymentRow=memo(function PaymentRow({payment}:{payment:PaymentSummary}){const open=useCallback(()=>router.push({pathname:'/payments/[payment-id]',params:{'payment-id':payment.id}}),[payment.id]);return <Pressable accessibilityRole="button" onPress={open} style={({pressed})=>[styles.row,pressed&&styles.pressed]}><View style={styles.copy}><View style={styles.titleLine}><Text selectable style={styles.number}>{payment.paNumber}</Text><Text selectable style={payment.state==='active'?styles.active:styles.voided}>{payment.state.toUpperCase()}</Text></View><Text selectable style={styles.customer}>{payment.customerName}</Text><Text selectable style={styles.meta}>{payment.billingStatementNumber} · {payment.businessDate}</Text></View><View style={styles.amountCopy}><Text selectable style={[styles.amount,payment.state==='voided'&&styles.strike]}>{formatCentavos(payment.amountCentavos)}</Text><Text selectable style={styles.meta}>{payment.pdfState.toUpperCase()}</Text></View></Pressable>});
export default function PaymentsScreen(){const db=useSQLiteContext();const[rows,setRows]=useState<PaymentSummary[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{setRows(await listPayments(db));}catch(e){setError(e instanceof Error?e.message:'Could not load payments.');}finally{setLoading(false);}},[db]);useFocusEffect(useCallback(()=>{void load();},[load]));return <FlatList contentInsetAdjustmentBehavior="automatic" contentContainerStyle={rows.length?styles.content:styles.emptyContent} data={rows} keyExtractor={(item)=>item.id} renderItem={({item})=><PaymentRow payment={item}/>} ItemSeparatorComponent={()=><View style={styles.separator}/>} refreshing={loading&&rows.length>0} onRefresh={load} ListHeaderComponent={<View style={styles.header}><Text selectable style={styles.eyebrow}>PAYMENT ACKNOWLEDGMENTS</Text><Text selectable style={styles.help}>Payments are recorded from a finalized Billing Statement. Corrections preserve the original as void.</Text>{error?<Text selectable style={styles.error}>{error}</Text>:null}</View>} ListEmptyComponent={loading?<ActivityIndicator color={colors.brandBlue} size="large"/>:<View style={styles.empty}><Text selectable style={styles.emptyTitle}>No payments yet</Text><Text selectable style={styles.help}>Open a finalized statement to record its required payment.</Text></View>}/>}
const styles=StyleSheet.create({content:{paddingHorizontal:18,paddingBottom:44},emptyContent:{flexGrow:1,paddingHorizontal:18,paddingBottom:44},header:{gap:8,paddingVertical:18},eyebrow:{color:colors.brandBlue,fontSize:11,fontWeight:'900',letterSpacing:1.2},help:{color:colors.secondaryLabel,fontSize:13,lineHeight:19},row:{minHeight:86,flexDirection:'row',alignItems:'center',gap:12,paddingVertical:13},copy:{flex:1,gap:4},titleLine:{flexDirection:'row',alignItems:'center',gap:8},number:{color:colors.label,fontSize:15,fontWeight:'900'},active:{color:colors.success,fontSize:8,fontWeight:'900'},voided:{color:colors.error,fontSize:8,fontWeight:'900'},customer:{color:colors.label,fontSize:14,fontWeight:'700'},meta:{color:colors.secondaryLabel,fontSize:10},amountCopy:{alignItems:'flex-end',gap:4},amount:{color:colors.brandNavy,fontSize:14,fontWeight:'900'},strike:{color:colors.secondaryLabel,textDecorationLine:'line-through'},separator:{height:StyleSheet.hairlineWidth,backgroundColor:colors.separator},empty:{flex:1,alignItems:'center',justifyContent:'center',gap:8},emptyTitle:{color:colors.label,fontSize:20,fontWeight:'900'},error:{color:colors.error,fontSize:13},pressed:{opacity:.72}});
