import * as Crypto from 'expo-crypto';
import * as DocumentPicker from 'expo-document-picker';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import type { SQLiteDatabase } from 'expo-sqlite';

import { appendAuditEvent, incrementDatabaseRevision } from '@/db/revision';
import type { SignableDocument, SignableOwnerType, SignatureStatus, SignedAttachment } from '@/features/signatures/signature-types';

type OwnerRow={id:string;document_number:string|null;customer_name:string;signature_status:SignatureStatus;document_state:SignableDocument['documentState']};
type AttachmentRow={id:string;deterministic_filename:string;private_path:string;checksum:string;created_at:string};

export async function getSignableDocument(db:SQLiteDatabase,ownerType:SignableOwnerType,ownerId:string):Promise<SignableDocument|null>{const owner=await getOwner(db,ownerType,ownerId);if(!owner)return null;const rows=await db.getAllAsync<AttachmentRow>(`SELECT id,deterministic_filename,private_path,checksum,created_at FROM document_attachments WHERE owner_type=? AND owner_id=? AND attachment_type='external_signed_pdf' ORDER BY created_at DESC,rowid DESC`,ownerType,ownerId);return{ownerType,ownerId,documentNumber:owner.document_number??'Unnumbered draft',customerName:owner.customer_name,signatureStatus:owner.signature_status,documentState:owner.document_state,attachments:rows.map(mapAttachment)};}

export async function setDocumentSignatureStatus(db:SQLiteDatabase,ownerType:SignableOwnerType,ownerId:string,status:Exclude<SignatureStatus,'signed_in_person'|'signed_document_attached'>):Promise<void>{const table=ownerType==='service_report'?'service_reports':'billing_statements';const now=new Date().toISOString();await db.withExclusiveTransactionAsync(async(tx)=>{const result=await tx.runAsync(`UPDATE ${table} SET signature_status=? WHERE id=? AND document_state='finalized'`,status,ownerId);if(result.changes!==1)throw new Error('Only a finalized document can change signing status.');await appendAuditEvent(tx,{eventType:'signature.status_changed',entityType:ownerType,entityId:ownerId,details:{status},createdAt:now});await incrementDatabaseRevision(tx);});}

export async function pickAndAttachSignedPdf(db:SQLiteDatabase,ownerType:SignableOwnerType,ownerId:string):Promise<string|null>{const result=await DocumentPicker.getDocumentAsync({type:'application/pdf',copyToCacheDirectory:true,multiple:false});if(result.canceled)return null;const asset=result.assets[0];if(asset.mimeType&&asset.mimeType!=='application/pdf'&&!asset.name.toLowerCase().endsWith('.pdf'))throw new Error('Select a PDF document.');return attachSignedPdf(db,ownerType,ownerId,asset.uri);}

export async function shareSignedAttachment(attachment:SignedAttachment):Promise<void>{if(!(await Sharing.isAvailableAsync()))throw new Error('File sharing is unavailable on this device.');await Sharing.shareAsync(attachment.privatePath,{dialogTitle:`Share ${attachment.filename}`,mimeType:'application/pdf',UTI:'com.adobe.pdf'});}

async function attachSignedPdf(db:SQLiteDatabase,ownerType:SignableOwnerType,ownerId:string,sourceUri:string):Promise<string>{const owner=await getOwner(db,ownerType,ownerId);if(!owner||owner.document_state!=='finalized'||!owner.document_number)throw new Error('Only a finalized numbered document can accept a signed PDF.');if(!FileSystem.documentDirectory)throw new Error('Persistent document storage is unavailable.');const count=await db.getFirstAsync<{count:number}>(`SELECT COUNT(*) AS count FROM document_attachments WHERE owner_type=? AND owner_id=? AND attachment_type='external_signed_pdf'`,ownerType,ownerId);const sequence=(count?.count??0)+1;const filename=`${owner.document_number}-signed-${String(sequence).padStart(2,'0')}.pdf`;const directory=`${FileSystem.documentDirectory}documents/signed/`;await FileSystem.makeDirectoryAsync(directory,{intermediates:true});const destination=`${directory}${filename}`;await FileSystem.copyAsync({from:sourceUri,to:destination});try{const base64=await FileSystem.readAsStringAsync(destination,{encoding:FileSystem.EncodingType.Base64});const checksum=await Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256,base64);const now=new Date().toISOString();await db.withExclusiveTransactionAsync(async(tx)=>{const current=await getOwner(tx,ownerType,ownerId);if(!current||current.document_state!=='finalized')throw new Error('Document state changed before the signed PDF was saved.');await tx.runAsync(`INSERT INTO document_attachments(id,owner_type,owner_id,attachment_type,deterministic_filename,private_path,checksum,created_at) VALUES(?,?,?,'external_signed_pdf',?,?,?,?)`,Crypto.randomUUID(),ownerType,ownerId,filename,destination,checksum,now);const table=ownerType==='service_report'?'service_reports':'billing_statements';await tx.runAsync(`UPDATE ${table} SET signature_status='signed_document_attached' WHERE id=?`,ownerId);await appendAuditEvent(tx,{eventType:'signature.external_pdf_attached',entityType:ownerType,entityId:ownerId,details:{filename,checksum},createdAt:now});await incrementDatabaseRevision(tx);});return destination;}catch(error){await FileSystem.deleteAsync(destination,{idempotent:true});throw error;}}

async function getOwner(db:SQLiteDatabase,ownerType:SignableOwnerType,ownerId:string):Promise<OwnerRow|null>{if(ownerType==='service_report')return db.getFirstAsync<OwnerRow>(`SELECT r.id,r.csr_number AS document_number,c.name AS customer_name,r.signature_status,r.document_state FROM service_reports r JOIN customers c ON c.id=r.customer_id WHERE r.id=?`,ownerId);return db.getFirstAsync<OwnerRow>(`SELECT b.id,b.bs_number AS document_number,c.name AS customer_name,b.signature_status,b.document_state FROM billing_statements b JOIN customers c ON c.id=b.customer_id WHERE b.id=?`,ownerId);}
function mapAttachment(row:AttachmentRow):SignedAttachment{return{id:row.id,filename:row.deterministic_filename,privatePath:row.private_path,checksum:row.checksum,createdAt:row.created_at};}
