import * as Crypto from 'expo-crypto';
import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { SQLiteDatabase } from 'expo-sqlite';

import { appendAuditEvent, incrementDatabaseRevision } from '@/db/revision';
import type { PaymentRenderResult } from '@/features/payments/payment-repository';

const A4_WIDTH_POINTS=595;
const A4_HEIGHT_POINTS=842;

export async function renderPaymentAcknowledgment(db:SQLiteDatabase,result:PaymentRenderResult):Promise<string>{return renderPaymentPdf(db,result.paymentId,result.paNumber,result.html);}
export async function retryPaymentPdf(db:SQLiteDatabase,paymentId:string):Promise<string>{const row=await db.getFirstAsync<{pa_number:string;render_template_snapshot:string|null}>("SELECT pa_number,render_template_snapshot FROM payments WHERE id=?",paymentId);if(!row?.pa_number||!row.render_template_snapshot)throw new Error('Payment acknowledgment snapshot is unavailable.');return renderPaymentPdf(db,paymentId,row.pa_number,row.render_template_snapshot);}
export async function sharePaymentPdf(db:SQLiteDatabase,paymentId:string):Promise<void>{const file=await db.getFirstAsync<{private_path:string;deterministic_filename:string}>(`SELECT private_path,deterministic_filename FROM document_attachments WHERE owner_type='payment' AND owner_id=? AND attachment_type='generated_pdf'`,paymentId);if(!file)throw new Error('Generate the Payment Acknowledgment PDF before sharing.');if(!(await Sharing.isAvailableAsync()))throw new Error('File sharing is unavailable on this device.');await Sharing.shareAsync(file.private_path,{dialogTitle:`Share ${file.deterministic_filename}`,mimeType:'application/pdf',UTI:'com.adobe.pdf'});await db.withExclusiveTransactionAsync(async(tx)=>{await tx.runAsync("UPDATE payments SET share_state='shared' WHERE id=?",paymentId);await appendAuditEvent(tx,{eventType:'payment.share_sheet_opened',entityType:'payment',entityId:paymentId,createdAt:new Date().toISOString()});await incrementDatabaseRevision(tx);});}

async function renderPaymentPdf(db:SQLiteDatabase,paymentId:string,paNumber:string,html:string):Promise<string>{try{const result=await Print.printToFileAsync({html,width:A4_WIDTH_POINTS,height:A4_HEIGHT_POINTS,base64:true,textZoom:100});if(!FileSystem.documentDirectory)throw new Error('Persistent document storage is unavailable.');if(!result.base64)throw new Error('PDF checksum source was not returned.');const directory=`${FileSystem.documentDirectory}documents/`;await FileSystem.makeDirectoryAsync(directory,{intermediates:true});const filename=`${paNumber}.pdf`;const destination=`${directory}${filename}`;const existing=await FileSystem.getInfoAsync(destination);if(existing.exists)await FileSystem.deleteAsync(destination,{idempotent:true});await FileSystem.moveAsync({from:result.uri,to:destination});const checksum=await Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256,result.base64);const now=new Date().toISOString();await db.withExclusiveTransactionAsync(async(tx)=>{const attachment=await tx.getFirstAsync<{id:string}>(`SELECT id FROM document_attachments WHERE owner_type='payment' AND owner_id=? AND attachment_type='generated_pdf'`,paymentId);if(attachment)await tx.runAsync('UPDATE document_attachments SET deterministic_filename=?,private_path=?,checksum=?,created_at=? WHERE id=?',filename,destination,checksum,now,attachment.id);else await tx.runAsync(`INSERT INTO document_attachments(id,owner_type,owner_id,attachment_type,deterministic_filename,private_path,checksum,created_at) VALUES(?,'payment',?,'generated_pdf',?,?,?,?)`,Crypto.randomUUID(),paymentId,filename,destination,checksum,now);await tx.runAsync("UPDATE payments SET pdf_state='ready' WHERE id=?",paymentId);await appendAuditEvent(tx,{eventType:'payment.pdf_rendered',entityType:'payment',entityId:paymentId,details:{numberOfPages:result.numberOfPages},createdAt:now});await incrementDatabaseRevision(tx);});return destination;}catch(error){await db.withExclusiveTransactionAsync(async(tx)=>{const changed=await tx.runAsync("UPDATE payments SET pdf_state='error' WHERE id=?",paymentId);if(changed.changes===1){await appendAuditEvent(tx,{eventType:'payment.pdf_error',entityType:'payment',entityId:paymentId,details:{message:error instanceof Error?error.message:String(error)},createdAt:new Date().toISOString()});await incrementDatabaseRevision(tx);}});throw error;}}
